openapi: 3.0.3
info:
    title: Chat API
    description: Chat API
    version: "0.1"
servers:
    - url: http://localhost:8000
paths:
    /api/channels:
        get:
            tags:
                - channels
            summary: list channels
            operationId: channels#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChannelList'
                            example:
                                items:
                                    - created_at: 2006-01-02T15:04:05Z07:00
                                      id: 14308298621592036455
                                      name: Voluptas error.
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                    - created_at: 2006-01-02T15:04:05Z07:00
                                      id: 14308298621592036455
                                      name: Voluptas error.
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                offset: 0
                                total: 160
        post:
            tags:
                - channels
            summary: create channels
            operationId: channels#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            name: Assumenda soluta atque commodi adipisci.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 15831009208318275754
                                name: Iste odio quas.
                                updated_at: 2006-01-02T15:04:05Z07:00
    /api/channels/{id}:
        delete:
            tags:
                - channels
            summary: delete channels
            operationId: channels#delete
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 6530557858022878942
                  example: 13767961240439804748
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 16656504247334610396
                                name: Perspiciatis optio rerum voluptatem est.
                                updated_at: 2006-01-02T15:04:05Z07:00
        get:
            tags:
                - channels
            summary: show channels
            operationId: channels#show
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 1560761711101387564
                  example: 1066760380926404989
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 11976032182583842327
                                name: Ut est ducimus.
                                updated_at: 2006-01-02T15:04:05Z07:00
        put:
            tags:
                - channels
            summary: update channels
            operationId: channels#update
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 8924780904197591867
                  example: 7735847978969038733
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            name: Sint nihil a et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 3571536357390730231
                                name: Repudiandae consequatur officia dolores corporis asperiores.
                                updated_at: 2006-01-02T15:04:05Z07:00
components:
    schemas:
        Channel:
            type: object
            properties:
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 10094222676920406623
                name:
                    type: string
                    description: Name
                    example: Voluptatibus beatae corrupti.
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
            example:
                created_at: 2006-01-02T15:04:05Z07:00
                id: 3174728128026383618
                name: Modi ullam excepturi earum.
                updated_at: 2006-01-02T15:04:05Z07:00
            required:
                - id
                - created_at
                - updated_at
                - name
        ChannelList:
            type: object
            properties:
                items:
                    $ref: '#/components/schemas/ChannelListItemCollection'
                offset:
                    type: integer
                    description: Offset
                    example: 0
                total:
                    type: integer
                    description: Total number of items
                    example: 160
            example:
                items:
                    - created_at: 2006-01-02T15:04:05Z07:00
                      id: 14308298621592036455
                      name: Voluptas error.
                      updated_at: 2006-01-02T15:04:05Z07:00
                    - created_at: 2006-01-02T15:04:05Z07:00
                      id: 14308298621592036455
                      name: Voluptas error.
                      updated_at: 2006-01-02T15:04:05Z07:00
                offset: 0
                total: 160
            required:
                - items
                - total
                - offset
        ChannelListItem:
            type: object
            properties:
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 994154316254792491
                name:
                    type: string
                    description: Name
                    example: Quia et.
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
            example:
                created_at: 2006-01-02T15:04:05Z07:00
                id: 11278499194749739618
                name: Cumque et ipsa voluptate ullam qui.
                updated_at: 2006-01-02T15:04:05Z07:00
            required:
                - id
                - created_at
                - updated_at
                - name
        ChannelListItemCollection:
            type: array
            items:
                $ref: '#/components/schemas/ChannelListItem'
            example:
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 14308298621592036455
                  name: Voluptas error.
                  updated_at: 2006-01-02T15:04:05Z07:00
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 14308298621592036455
                  name: Voluptas error.
                  updated_at: 2006-01-02T15:04:05Z07:00
        CreateRequestBody:
            type: object
            properties:
                name:
                    type: string
                    description: Name
                    example: Sed sed ut quibusdam ea.
            example:
                name: Recusandae quo ratione et.
            required:
                - name
tags:
    - name: channels
