.PHONY: default
default: build

.PHONY: build
build:
	$(MAKE) -C apisvr build

.PHONY: lint
lint:
	$(MAKE) -C apisvr lint

.PHONY: test
test:
	$(MAKE) -C apisvr test

.PHONY: dev
dev:
	$(MAKE) -C apisvr dev
