// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Channels", testChannelsUpsert)

	t.Run("ChatMessages", testChatMessagesUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Users", testUsersUpsert)
}
