version: "3.7"
name: "sk_goa_chat_swaggerui"
services:
  swaggerui:
    # platform: linux/amd64
    image: swaggerapi/swagger-ui:v5.11.0
    container_name: swaggerui
    restart: always
    ports:
      - "${SWAGGERUI_PORT}:8080"
    # https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
    environment:
      SWAGGER_JSON: ${SWAGGERUI_JSON_PATH}
      WITH_CREDENTIALS: "true"
    volumes:
      - ../../backend/apisvr:/srv/apisvr
    networks:
      - network1

networks:
  network1:
