.PHONY: default
default: build lint test

include ../../.config.mk
include ./Makefiles/asdf.mk
include ./Makefiles/git_check.mk
include ./Makefiles/dev.mk
include ./Makefiles/go.mk
include ./Makefiles/goa.mk
include ./Makefiles/lint.mk
include ./Makefiles/run.mk
include ./Makefiles/sqlboiler.mk
include ./Makefiles/test.mk
