# このファイルは以下の２つのファイルから読み込まれます
# - frontend/tests/integration/Makefile
# - frontend/tests/integration/containers/Makefile
APP_APISVR_HTTP_PORT=8001
APP_APISVR_GRPC_PORT=8081
APP_FIREBASE_AUTH_PORT=9090
ENVS=\
	APP_ENV=e2e_test \
	APP_MYSQL_DATABASE_NAME=$(APP_MYSQL_DATABASE_NAME) \
	APP_MYSQL_PORT=3307 \
	APP_FIREBASE_AUTH_PORT=$(APP_FIREBASE_AUTH_PORT) \
	APP_APISVR_HTTP_PORT=$(APISVR_HTTP_PORT) \
	APP_APISVR_GRPC_PORT=$(APISVR_GRPC_PORT)

.PHONY: envs
envs:
	@echo $(ENVS)
