APISVR_HTTP_PORT=8001
APISVR_GRPC_PORT=8081
FIREBASE_AUTH_PORT=9090
ENVS=\
	ENV_TYPE=e2e_test \
	MYSQL_DATABASE_NAME=$(MYSQL_DATABASE_NAME) \
	MYSQL_PORT=3307 \
	FIREBASE_AUTH_PORT=$(FIREBASE_AUTH_PORT) \
	APISVR_HTTP_PORT=$(APISVR_HTTP_PORT) \
	APISVR_GRPC_PORT=$(APISVR_GRPC_PORT)

.PHONY: envs
envs:
	@echo $(ENVS)
