// https://firebase.google.com/docs/auth/admin/errors?hl=ja
export const messageKeys = [
	'auth/account-exists-with-different-credential',
	'auth/claims-too-large',
	'auth/email-already-exists',
	'auth/email-already-in-use',
	'auth/id-token-expired',
	'auth/id-token-revoked',
	'auth/insufficient-permission',
	'auth/internal-error',
	'auth/invalid-argument',
	'auth/invalid-claims',
	'auth/invalid-continue-uri',
	'auth/invalid-creation-time',
	'auth/invalid-credential',
	'auth/invalid-disabled-field',
	'auth/invalid-display-name',
	'auth/invalid-dynamic-link-domain',
	'auth/invalid-email',
	'auth/invalid-email-verified',
	'auth/invalid-hash-algorithm',
	'auth/invalid-hash-block-size',
	'auth/invalid-hash-derived-key-length',
	'auth/invalid-hash-key',
	'auth/invalid-hash-memory-cost',
	'auth/invalid-hash-parallelization',
	'auth/invalid-hash-rounds',
	'auth/invalid-hash-salt-separator',
	'auth/invalid-id-token',
	'auth/invalid-last-sign-in-time',
	'auth/invalid-oauth-responsetype',
	'auth/invalid-page-token',
	'auth/invalid-password',
	'auth/invalid-password-hash',
	'auth/invalid-password-salt',
	'auth/invalid-phone-number',
	'auth/invalid-photo-url',
	'auth/invalid-provider-data',
	'auth/invalid-provider-id',
	'auth/invalid-session-cookie-duration',
	'auth/invalid-uid',
	'auth/invalid-user-import',
	'auth/invalid-verification-code',
	'auth/invalid-verification-id',
	'auth/maximum-user-count-exceeded',
	'auth/missing-android-pkg-name',
	'auth/missing-continue-uri',
	'auth/missing-hash-algorithm',
	'auth/missing-ios-bundle-id',
	'auth/missing-oauth-client-secret',
	'auth/missing-password',
	'auth/missing-uid',
	'auth/operation-not-allowed',
	'auth/session-cookie-revoked',
	'auth/user-disabled',
	'auth/user-not-found',
	'auth/weak-password',
	'auth/wrong-password'
] as const;

export type MessageKey = (typeof messageKeys)[number];

export const isMessageKey = (value: string): value is MessageKey => {
	return messageKeys.includes(value as MessageKey);
};
