PATH_TO_UISVR:=../../..
PATH_TO_PROJECT:=$(PATH_TO_UISVR)/../..
PATH_TO_FUKOWL_ROOT=$(PATH_TO_PROJECT)/vendor/fukowl
PATH_TO_FUKOWL_MAKEFILES=$(PATH_TO_FUKOWL_ROOT)/makefiles

include $(PATH_TO_PROJECT)/.config.mk
include ../envs.mk

include $(PATH_TO_FUKOWL_MAKEFILES)/locale2e/containers.mk
