PATH_TO_UISVR:=../../..
PATH_TO_PROJECT:=$(PATH_TO_UISVR)/../..
PATH_TO_GOAVELTE_MAKEFILES=$(PATH_TO_PROJECT)/vendor/goavelte/makefiles

include $(PATH_TO_PROJECT)/.config.mk
include $(PATH_TO_GOAVELTE_MAKEFILES)/locale2e/envs.mk
include $(PATH_TO_GOAVELTE_MAKEFILES)/locale2e/containers.mk
