// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "goagen_services_chat_messages.proto" (package "chat_messages", syntax proto3)
// tslint:disable
//
// Code generated with goa v3.14.1, DO NOT EDIT.
//
// chat_messages protocol buffer definition
//
// Command:
// $ goa gen apisvr/design -o ./services
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ChatMessages } from "./goagen_services_chat_messages";
import type { DeleteResponse } from "./goagen_services_chat_messages";
import type { DeleteRequest } from "./goagen_services_chat_messages";
import type { UpdateResponse } from "./goagen_services_chat_messages";
import type { UpdateRequest } from "./goagen_services_chat_messages";
import type { CreateResponse } from "./goagen_services_chat_messages";
import type { CreateRequest } from "./goagen_services_chat_messages";
import type { ShowResponse } from "./goagen_services_chat_messages";
import type { ShowRequest } from "./goagen_services_chat_messages";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListResponse } from "./goagen_services_chat_messages";
import type { ListRequest } from "./goagen_services_chat_messages";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Service is the chat_messages service interface.
 *
 * @generated from protobuf service chat_messages.ChatMessages
 */
export interface IChatMessagesClient {
    /**
     * List implements list.
     *
     * @generated from protobuf rpc: List(chat_messages.ListRequest) returns (chat_messages.ListResponse);
     */
    list(input: ListRequest, options?: RpcOptions): UnaryCall<ListRequest, ListResponse>;
    /**
     * Show implements show.
     *
     * @generated from protobuf rpc: Show(chat_messages.ShowRequest) returns (chat_messages.ShowResponse);
     */
    show(input: ShowRequest, options?: RpcOptions): UnaryCall<ShowRequest, ShowResponse>;
    /**
     * Create implements create.
     *
     * @generated from protobuf rpc: Create(chat_messages.CreateRequest) returns (chat_messages.CreateResponse);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse>;
    /**
     * Update implements update.
     *
     * @generated from protobuf rpc: Update(chat_messages.UpdateRequest) returns (chat_messages.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * Delete implements delete.
     *
     * @generated from protobuf rpc: Delete(chat_messages.DeleteRequest) returns (chat_messages.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * Service is the chat_messages service interface.
 *
 * @generated from protobuf service chat_messages.ChatMessages
 */
export class ChatMessagesClient implements IChatMessagesClient, ServiceInfo {
    typeName = ChatMessages.typeName;
    methods = ChatMessages.methods;
    options = ChatMessages.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * List implements list.
     *
     * @generated from protobuf rpc: List(chat_messages.ListRequest) returns (chat_messages.ListResponse);
     */
    list(input: ListRequest, options?: RpcOptions): UnaryCall<ListRequest, ListResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRequest, ListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Show implements show.
     *
     * @generated from protobuf rpc: Show(chat_messages.ShowRequest) returns (chat_messages.ShowResponse);
     */
    show(input: ShowRequest, options?: RpcOptions): UnaryCall<ShowRequest, ShowResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShowRequest, ShowResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Create implements create.
     *
     * @generated from protobuf rpc: Create(chat_messages.CreateRequest) returns (chat_messages.CreateResponse);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRequest, CreateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Update implements update.
     *
     * @generated from protobuf rpc: Update(chat_messages.UpdateRequest) returns (chat_messages.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Delete implements delete.
     *
     * @generated from protobuf rpc: Delete(chat_messages.DeleteRequest) returns (chat_messages.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
