// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "goagen_services_channels.proto" (package "channels", syntax proto3)
// tslint:disable
//
// Code generated with goa v3.14.0, DO NOT EDIT.
//
// channels protocol buffer definition
//
// Command:
// $ goa gen apisvr/design -o ./services
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Channels } from "./goagen_services_channels";
import type { DeleteResponse } from "./goagen_services_channels";
import type { DeleteRequest } from "./goagen_services_channels";
import type { UpdateResponse } from "./goagen_services_channels";
import type { UpdateRequest } from "./goagen_services_channels";
import type { CreateResponse } from "./goagen_services_channels";
import type { CreateRequest } from "./goagen_services_channels";
import type { ShowResponse } from "./goagen_services_channels";
import type { ShowRequest } from "./goagen_services_channels";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListResponse } from "./goagen_services_channels";
import type { ListRequest } from "./goagen_services_channels";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Service is the channels service interface.
 *
 * @generated from protobuf service channels.Channels
 */
export interface IChannelsClient {
    /**
     * List implements list.
     *
     * @generated from protobuf rpc: List(channels.ListRequest) returns (channels.ListResponse);
     */
    list(input: ListRequest, options?: RpcOptions): UnaryCall<ListRequest, ListResponse>;
    /**
     * Show implements show.
     *
     * @generated from protobuf rpc: Show(channels.ShowRequest) returns (channels.ShowResponse);
     */
    show(input: ShowRequest, options?: RpcOptions): UnaryCall<ShowRequest, ShowResponse>;
    /**
     * Create implements create.
     *
     * @generated from protobuf rpc: Create(channels.CreateRequest) returns (channels.CreateResponse);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse>;
    /**
     * Update implements update.
     *
     * @generated from protobuf rpc: Update(channels.UpdateRequest) returns (channels.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * Delete implements delete.
     *
     * @generated from protobuf rpc: Delete(channels.DeleteRequest) returns (channels.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * Service is the channels service interface.
 *
 * @generated from protobuf service channels.Channels
 */
export class ChannelsClient implements IChannelsClient, ServiceInfo {
    typeName = Channels.typeName;
    methods = Channels.methods;
    options = Channels.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * List implements list.
     *
     * @generated from protobuf rpc: List(channels.ListRequest) returns (channels.ListResponse);
     */
    list(input: ListRequest, options?: RpcOptions): UnaryCall<ListRequest, ListResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRequest, ListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Show implements show.
     *
     * @generated from protobuf rpc: Show(channels.ShowRequest) returns (channels.ShowResponse);
     */
    show(input: ShowRequest, options?: RpcOptions): UnaryCall<ShowRequest, ShowResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShowRequest, ShowResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Create implements create.
     *
     * @generated from protobuf rpc: Create(channels.CreateRequest) returns (channels.CreateResponse);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRequest, CreateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Update implements update.
     *
     * @generated from protobuf rpc: Update(channels.UpdateRequest) returns (channels.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Delete implements delete.
     *
     * @generated from protobuf rpc: Delete(channels.DeleteRequest) returns (channels.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
