// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channels       string
	ChatMessages   string
	GooseDBVersion string
	Users          string
}{
	Channels:       "channels",
	ChatMessages:   "chat_messages",
	GooseDBVersion: "goose_db_version",
	Users:          "users",
}
