.PHONY: default
default: build test

include ../config.mk
include ./Makefiles/dev.mk
include ./Makefiles/go.mk
include ./Makefiles/goa.mk
include ./Makefiles/lint.mk
include ./Makefiles/sqlboiler.mk
include ./Makefiles/test.mk
