ENVS=\
	ENV_TYPE=e2e_test \
	MYSQL_DATABASE_NAME=$(MYSQL_DATABASE_NAME) \
	MYSQL_PORT=3307 \
	FIREBASE_AUTH_PORT=9090 \
	APISVR_HTTP_PORT=8081 \
	APISVR_GRPC_PORT=8001

.PHONY: envs
envs:
	@echo $(ENVS)
