# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: apisvr CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/**"
      - "apisvr/**"
      - "containers/**"
      - "dbmigrations/**"
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "apisvr/go.mod"

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker-compose -v
          docker compose version
          docker version

      - name: Install firebase tools
        run: npm install -g firebase-tools
        working-directory: ./ui

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      - name: build
        run: make build
        working-directory: ./apisvr

      - name: lint
        run: make lint
        working-directory: ./apisvr

      - name: test
        run: make test
        working-directory: ./apisvr
