# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: servers apisvr gen CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/**"
      - ".gitignore"
      - ".tool-versions"
      - "servers/apisvr/Makefile"
      - "servers/apisvr/Makefiles/**"
      - "servers/apisvr/design/**"
      - "servers/replacements/apisvr/**"
      - ".config.mk"
      - "Makefile"
      # - "modifiers"
      # - "tools/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "servers/apisvr/go.mod"

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker-compose -v
          docker compose version
          docker version

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Check ruby version
        run: |
          set -x
          ruby -v
          gem env
          gem list

      # https://github.com/marketplace/actions/setup-protoc
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.1"

      - name: goa_gen_ci
        run: make goa_gen_ci
        working-directory: ./servers/apisvr

      - name: goa_example_ci
        run: make goa_example_ci
        working-directory: ./servers/apisvr
