# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: servers biz gen CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/**"
      - ".gitignore"
      - ".tool-versions"
      - "servers/applib/**"
      - "servers/biz/**"
      - "servers/containers/**"
      - "servers/dbmigrations/**"
      - "servers/replacements/*"
      - "servers/replacements/biz/**"
      - ".config.mk"
      - "Makefile"
      # - "modifiers"
      # - "tools/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "servers/biz/go.mod"

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker-compose -v
          docker compose version
          docker version

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      - name: sqlboiler_gen_ci
        run: make sqlboiler_gen_ci
        working-directory: ./servers/biz
