# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: servers biz gen CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/**"
      - ".gitignore"
      - ".tool-versions"
      - "servers/applib/**"
      - "servers/biz/**"
      - "servers/containers/**"
      - "servers/dbmigrations/**"
      - "servers/replacements/*"
      - "servers/replacements/biz/**"
      - ".config.mk"
      - "Makefile"
      # - "modifiers"
      # - "tools/**"
      - "vendor/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "servers/biz/go.mod"

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker-compose -v
          docker compose version
          docker version

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Check ruby version
        run: |
          set -x
          ruby -v
          gem env
          gem list

      - name: sqlboiler_gen
        run: make sqlboiler_gen
        working-directory: ./servers/biz
        env:
          APP_SKIP_DB_SCHEMA_DUMP: "true"

      - name: git_check
        run: make git_check
        working-directory: ./servers/apisvr
